In [4]:
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [8]:
vocab_size=10000

**One hot Encoding**

In [10]:
#one hot encoding
onehot_repr=[one_hot(words,vocab_size)for words in sent]
print(onehot_repr)

[[3151, 6577, 4232, 6632], [3151, 6577, 4232, 7988], [3151, 2687, 4232, 7726], [7996, 1902, 7317, 2995, 1926], [7996, 1902, 7317, 2995, 8990], [4765, 3151, 5228, 4232, 9635], [5095, 9543, 4520, 2995]]


**word embedding representation**

In [12]:
#word embedding representation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [13]:
import numpy as np

In [14]:
sent_length=8
embedded_docs = pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 3151 6577 4232 6632]
 [   0    0    0    0 3151 6577 4232 7988]
 [   0    0    0    0 3151 2687 4232 7726]
 [   0    0    0 7996 1902 7317 2995 1926]
 [   0    0    0 7996 1902 7317 2995 8990]
 [   0    0    0 4765 3151 5228 4232 9635]
 [   0    0    0    0 5095 9543 4520 2995]]


In [15]:
#padding will look the words in the sentences and then match it with the 
#length of the sent if it exceeds it will add padding of 0's to it.

In [16]:
dim=10

In [19]:
model=Sequential()
model.add(Embedding(vocab_size,10,input_length=sent_length))
model.compile('adam','mse')

In [20]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 8, 10)             100000    
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [21]:
print(model.predict(embedded_docs))

[[[-0.04426599  0.02178129 -0.03267033 -0.04982026 -0.03746044
   -0.01831136  0.0232934  -0.00181233  0.01332662  0.02206613]
  [-0.04426599  0.02178129 -0.03267033 -0.04982026 -0.03746044
   -0.01831136  0.0232934  -0.00181233  0.01332662  0.02206613]
  [-0.04426599  0.02178129 -0.03267033 -0.04982026 -0.03746044
   -0.01831136  0.0232934  -0.00181233  0.01332662  0.02206613]
  [-0.04426599  0.02178129 -0.03267033 -0.04982026 -0.03746044
   -0.01831136  0.0232934  -0.00181233  0.01332662  0.02206613]
  [-0.01879857  0.02171112 -0.01904221 -0.01199568 -0.01879591
    0.01355052 -0.04061329  0.04777581 -0.01394045  0.02067752]
  [-0.01419546  0.04297581 -0.02542673  0.00650769 -0.00649569
   -0.03839101  0.01677109  0.01641161  0.03112537  0.04410787]
  [ 0.04780765 -0.03882458 -0.04384438  0.02021961  0.02405467
    0.0414005  -0.036582   -0.04207134 -0.01131741 -0.00045602]
  [ 0.02950603  0.04742266  0.04477694 -0.01049208 -0.00077134
   -0.00881723 -0.0471333  -0.00449767 -0.045517

In [22]:
embedded_docs[0]

array([   0,    0,    0,    0, 3151, 6577, 4232, 6632], dtype=int32)

In [24]:
print(model.predict(embedded_docs)[0])

[[-0.04426599  0.02178129 -0.03267033 -0.04982026 -0.03746044 -0.01831136
   0.0232934  -0.00181233  0.01332662  0.02206613]
 [-0.04426599  0.02178129 -0.03267033 -0.04982026 -0.03746044 -0.01831136
   0.0232934  -0.00181233  0.01332662  0.02206613]
 [-0.04426599  0.02178129 -0.03267033 -0.04982026 -0.03746044 -0.01831136
   0.0232934  -0.00181233  0.01332662  0.02206613]
 [-0.04426599  0.02178129 -0.03267033 -0.04982026 -0.03746044 -0.01831136
   0.0232934  -0.00181233  0.01332662  0.02206613]
 [-0.01879857  0.02171112 -0.01904221 -0.01199568 -0.01879591  0.01355052
  -0.04061329  0.04777581 -0.01394045  0.02067752]
 [-0.01419546  0.04297581 -0.02542673  0.00650769 -0.00649569 -0.03839101
   0.01677109  0.01641161  0.03112537  0.04410787]
 [ 0.04780765 -0.03882458 -0.04384438  0.02021961  0.02405467  0.0414005
  -0.036582   -0.04207134 -0.01131741 -0.00045602]
 [ 0.02950603  0.04742266  0.04477694 -0.01049208 -0.00077134 -0.00881723
  -0.0471333  -0.00449767 -0.04551703 -0.01061196]]
